service: aws-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:sa-east-1:130962141822:table/UserTable
	
resources: # CloudFormation template syntax
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


functions:
  handler:
    handler: 'src/handler.handler'
    events:
      - httpApi:
          path: /
          method: get
  createUser:
    handler: 'src/createUser.createUser'
    events:
      - httpApi:
          path: /user
          method: post
  getUsers:
    handler: 'src/getUsers.getUsers'
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: 'src/getUser.getUser'
    events:
      - httpApi:
        path: /user/{id}
        method: get
        request:
          parameters:
            paths:
              id: true
